name: buld-docker-images

on:
  workflow_call:
    inputs:
      version:
        description: 'version tag for docker image building'
        type: string
        default: 'latest'
        required: true

env:
  REGISTRY: ghcr.io
  BACKEND_IMAGE_NAME: 'zetroot/safehouseams.back'
  FRONTEND_IMAGE_NAME: 'zetroot/safehouseams.front'

jobs:
  backend:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v1.14.1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2.9.0
        with:
          context: .
          file: 'Dockerfile'
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE_NAME }}:${{ inputs.version }}

  forntend:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v1.14.1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2.9.0
        with:
          context: .
          file: 'Dockerfile.wasm'
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}:${{ inputs.version }}
